import Head from 'next/head'
import axios from 'axios';
import { Inter } from 'next/font/google';
import Main from './flags';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ flags }: any) {
	return (
		<>
			<Head>
				<title>World Flag | Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Main flags={flags} />
			</main>
		</>
	);
}

export async function getServerSideProps() {
	const result = await axios.get('https://restcountries.com/v3.1/all');
	// const res = await fetch()
	return {
		props: {
			flags: result.data,
		},
	};
}
